services:
  backend:
    image: golang:1.24.3-bookworm
    container_name: global_chat_backend
    depends_on:
      - database
      - web-server
    volumes:
      - ./src/backend:/opt/global_chat
    ports:
      - 8080:8080
    working_dir: /opt/global_chat
    stdin_open: true
    tty: true
  database:
    image: postgres:latest
    container_name: global_chat_database
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 1111
    volumes:
      - ./src/database:/opt/global_chat/sql
      - ./docker/database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
  web-server:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./src/frontend:/usr/share/nginx/html:ro
    ports:
      - '80:80'

volumes:
  postgres_data: